### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by whutddk** [potterhere/Freescale_K60-KL26_NRF#1]
* 感觉蓝牙，nrf都有比较大的局限性，很老的方案了，带宽小，不稳定
* 如果是从上位机开始写，建议尝试一下ESP8266,走wifi路线，tcp或者udp协议
* 嵌入式端ESP如果简单操作用串口就行，可以达到非常高的波特率，或者走spi，速度可以更高。

**Comment by Sudouble** [comment]
刚看到issue。那时候用NRF确实也有出现过信号干扰的问题。那时候主要也精力有限，刚开发出初版就拿去用了。后期收到的建议不多，主要以维护为主了。
总之，很棒的一个想法！
